version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: dev.dockerfile
    image: dev_csv_backend
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./:/app
      - ./conf/.env.development:/app/.env

  mongodb:
    image: mongo:6.0.5-jammy
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: csv_dev
